// flow-typed signature: 3a65b5df00828a1ad2312e588c49c81a
// flow-typed version: <<STUB>>/babel-plugin-import-inspector_v^2.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-import-inspector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-import-inspector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-import-inspector/index' {
  declare module.exports: $Exports<'babel-plugin-import-inspector'>;
}
declare module 'babel-plugin-import-inspector/index.js' {
  declare module.exports: $Exports<'babel-plugin-import-inspector'>;
}
