// flow-typed signature: e5fc6b44d960b53a30e2259026e9cbce
// flow-typed version: <<STUB>>/import-inspector_v^2.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'import-inspector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'import-inspector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'import-inspector/index' {
  declare module.exports: $Exports<'import-inspector'>;
}
declare module 'import-inspector/index.js' {
  declare module.exports: $Exports<'import-inspector'>;
}
